version: "3"

services:

  factorio:
    image: factoriotools/factorio
    container_name: factorio
    restart: always
    volumes:
      - "factorio-data:/factorio"
    ports:
      - "34197:34197/udp"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - FACTORIO_SERVER_NAME=Glitch Factorio Server
      - FACTORIO_SERVER_DESCRIPTION=Welcome to Glitch Factorio server!
      - FACTORIO_SERVER_VISIBILITY=public
      - FACTORIO_SERVER_GAME_PASSWORD=f@ct0ry
      - FACTORIO_SERVER_MAX_PLAYERS=10
      - FACTORIO_SERVER_ALLOW_COMMANDS=true
      - FACTORIO_SERVER_AUTOSAVE_INTERVAL=10
      - FACTORIO_SERVER_AUTOSAVE_SLOTS=5
volumes:
  factorio-data:
      driver: local
      driver_opts:
        type: nfs
        o: addr=192.168.1.X,rw
        device: ":/mnt/<PATH TO NFS SHARE>/factorio"
